// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// ✅ Import the generated sidebar for sandbox
import sandbox from "./docs/sandbox/sidebar.js";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: "doc", id: "intro" },
    { type: "autogenerated", dirName: "tutorial-basics" },
    { type: "autogenerated", dirName: "tutorial-extras" },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "Sandbox",
      link: {
        type: "generated-index",
        title: "Sandbox API",
        description: "Explore the Recall Network's sandbox API for autonomous agent proofs and storage.",
        slug: "/category/sandbox-api",
      },
      items: sandbox,
    },
  ],
};

export default sidebars;


